"""
Synthetic "filler" cards for the Today dashboard: the account-, contact-,
and discovery-based nudges shown when an agent doesn't have enough real
SuggestedAction/FlowRecommendation cards to fill out the Today tab (most
obviously a brand-new account, but any time the real queue runs dry).

Unlike those two, filler cards aren't generated by a nightly job and
stored -- they're computed fresh on every dashboard load from the rules
below plus live data, and only remembered (in FillerActionState) once an
agent resolves one (taps the CTA or dismisses it), so a resolved one
never reappears. See FillerActionState's docstring for that model.

Reference doc for this list (categories, priority order, what's
deliberately deferred to later -- habit-forming/re-engagement and
education/trust-building cards): the "&Gifts -- Today Tab Filler
Actions" doc shared with Jeremiah. Keep FILLER_KEY constants and tier
grouping here in sync with that doc when the list changes.

Deviations from that doc, made while wiring this up against the actual
app (flag these back to Jeremiah if the doc should be updated to match):
  - FILL-ACC-03 "Verify your email" dropped: login already blocks an
    unverified user before they can ever reach the dashboard (see
    auth.login), so this state is unreachable here.
  - FILL-ACC-04 "Set up outreach preferences" dropped: the sender
    identity is auto-generated at org creation and the settings page
    for it is org-admin-only, not a natural per-agent Today-tab nudge.
  - FILL-CON-07 "Import contacts" retargeted to "Add more contacts"
    (-> new-contact form) since there's no CSV/phone import feature yet.
  - FILL-DIS-02 "Browse gift price tiers" dropped as a near-duplicate of
    FILL-DIS-01 (both just point at the same catalog page).

To add a new filler action:
  1. Add a FillerDefinition to REGISTRY below, in the right tier.
  2. If it's per-contact (evaluated against individual contacts rather
     than the account as a whole), set per_contact=True and provide
     contact_query instead of condition -- see FILL-CON-03/04/05.
  3. Provide cta_endpoint (+ cta_kwargs if it needs args) so _build_url
     and the dashboard's /go route know where to send the agent.
"""
from datetime import datetime, timedelta

from flask import url_for

from app.extensions import db
from app.models.actions import FillerActionState

# --- Tunables ----------------------------------------------------------
STALE_CONTACT_DAYS = 60          # FILL-CON-02 / FILL-CON-03 threshold
MAX_PER_CONTACT_CARDS = 2        # cap per per-contact filler type, per dashboard load
LOW_CONTACT_COUNT_THRESHOLD = 5  # FILL-CON-07

TIER_ACCOUNT, TIER_CONTACT, TIER_DISCOVERY = 1, 2, 3

# How many total cards (real + filler) the Today tab tries to show.
# Filler only ever tops up the real queue, never crowds it out -- see
# generate_filler_cards's `limit` param, computed in dashboard.index as
# TARGET_CARD_COUNT minus however many real cards already exist.
TARGET_CARD_COUNT = 5


class FillerCard:
    """A single rendered filler card -- built fresh each request, never
    persisted itself (see FillerActionState for what IS persisted)."""
    item_kind = "filler"

    def __init__(self, key, tier, title, reason_text, cta_label, cta_url, contact=None):
        self.id = key  # matches SuggestedAction/FlowRecommendation's `s.id` usage in templates
        self.key = key
        self.tier = tier
        self.title = title
        self.reason_text = reason_text
        self.cta_label = cta_label
        self.cta_url = cta_url
        self.contact = contact


class FillerDefinition:
    """One row in REGISTRY -- see module docstring for how to add one."""

    def __init__(
        self, key, tier, title, reason_text, cta_label, cta_endpoint,
        condition=None, per_contact=False, contact_query=None, cta_kwargs=None,
    ):
        self.key = key
        self.tier = tier
        self.title = title
        self.reason_text = reason_text
        self.cta_label = cta_label
        self.cta_endpoint = cta_endpoint
        self.condition = condition
        self.per_contact = per_contact
        self.contact_query = contact_query
        self.cta_kwargs = cta_kwargs or (lambda user, contact=None: {})


def _build_url(definition, user, contact=None):
    return url_for(definition.cta_endpoint, **definition.cta_kwargs(user, contact))


# --- Tier 1 conditions: account-based -----------------------------------

def _no_payment_method(user):
    return len(user.payment_methods) == 0


def _no_profile_photo(user):
    return not user.photo_url


def _can_invite_teammate(user):
    if not user.is_admin:
        return False
    seat_limit = user.org.limit_for("seats")
    if seat_limit is not None and seat_limit <= 1:
        return False
    active_count = sum(1 for u in user.org.users if u.status == "active")
    return active_count <= 1


# --- Tier 2 conditions: contact-based ------------------------------------

def _no_contacts(user):
    return user.org.contact_count() == 0


def _no_recent_contact(user):
    from app.models import Contact
    if user.org.contact_count() == 0:
        return False
    most_recent = (
        Contact.query.filter_by(org_id=user.org_id)
        .order_by(Contact.created_at.desc())
        .first()
    )
    cutoff = datetime.utcnow() - timedelta(days=STALE_CONTACT_DAYS)
    return most_recent is not None and most_recent.created_at < cutoff


def _low_contact_count(user):
    count = user.org.contact_count()
    return 0 < count < LOW_CONTACT_COUNT_THRESHOLD


def _contacts_missing_badge(user):
    from app.models import Contact
    query = Contact.visible_to(Contact.query.filter_by(org_id=user.org_id), user)
    return [c for c in query.all() if not c.badges]


def _stale_contacts_query(user):
    from app.models import Contact
    cutoff = datetime.utcnow() - timedelta(days=STALE_CONTACT_DAYS)
    query = Contact.visible_to(
        Contact.query.filter_by(org_id=user.org_id).filter(Contact.updated_at < cutoff), user
    )
    return query.order_by(Contact.updated_at.asc()).all()


def _contacts_missing_occasion_query(user):
    from app.models import Contact
    query = Contact.visible_to(Contact.query.filter_by(org_id=user.org_id), user)
    return [c for c in query.all() if not c.important_dates]


def _contacts_missing_shipping_query(user):
    from app.models import Contact
    query = Contact.visible_to(Contact.query.filter_by(org_id=user.org_id), user)
    return [c for c in query.all() if not c.has_shipping_address]


# --- Tier 3 conditions: discovery-based -----------------------------------

def _no_flows(user):
    from app.models.campaigns import Campaign
    q = Campaign.query.filter_by(org_id=user.org_id).filter(
        db.or_(Campaign.owner_user_id.is_(None), Campaign.owner_user_id == user.id)
    )
    return q.count() == 0


# --- Registry --------------------------------------------------------------

REGISTRY = [
    FillerDefinition(
        key="FILL-ACC-01",
        tier=TIER_ACCOUNT,
        title="Add a payment card on file",
        reason_text="Approving a gift or handwritten note charges your saved card -- add one now so nothing's held up when you approve your first one.",
        cta_label="Add a card",
        cta_endpoint="settings.payment_methods",
        condition=_no_payment_method,
    ),
    FillerDefinition(
        key="FILL-ACC-02",
        tier=TIER_ACCOUNT,
        title="Add a profile photo",
        reason_text="A quick personal touch -- add a photo to your profile.",
        cta_label="Edit profile",
        cta_endpoint="profile.edit_profile",
        condition=_no_profile_photo,
    ),
    FillerDefinition(
        key="FILL-ACC-05",
        tier=TIER_ACCOUNT,
        title="Invite a teammate",
        reason_text="Your plan supports more than one seat -- bring a teammate onto the account.",
        cta_label="Invite teammate",
        cta_endpoint="team.new_member",
        condition=_can_invite_teammate,
    ),

    FillerDefinition(
        key="FILL-CON-01",
        tier=TIER_CONTACT,
        title="Add your first contact",
        reason_text="Add a contact to start getting gift and outreach suggestions.",
        cta_label="Add a contact",
        cta_endpoint="contacts.new_contact",
        condition=_no_contacts,
    ),
    FillerDefinition(
        key="FILL-CON-02",
        tier=TIER_CONTACT,
        title="It's been a while since you added a contact",
        reason_text=f"No new contact in the last {STALE_CONTACT_DAYS} days -- add one to keep suggestions coming.",
        cta_label="Add a contact",
        cta_endpoint="contacts.new_contact",
        condition=_no_recent_contact,
    ),
    FillerDefinition(
        key="FILL-CON-07",
        tier=TIER_CONTACT,
        title="Add more contacts",
        reason_text="A bigger contact list means more gift and outreach suggestions down the road.",
        cta_label="Add a contact",
        cta_endpoint="contacts.new_contact",
        condition=_low_contact_count,
    ),
    FillerDefinition(
        key="FILL-CON-06",
        tier=TIER_CONTACT,
        title="Tag your contacts",
        reason_text="Badges (VIP, Family Friend, etc.) help you spot who matters most at a glance.",
        cta_label="Review contacts",
        cta_endpoint="contacts.list_contacts",
        condition=lambda user: len(_contacts_missing_badge(user)) > 0,
    ),
    FillerDefinition(
        key="FILL-CON-03",
        tier=TIER_CONTACT,
        title="It's been a while since you updated {contact}",
        reason_text="Keeping contact records current means better-timed suggestions.",
        cta_label="Update contact",
        cta_endpoint="contacts.edit_contact",
        per_contact=True,
        contact_query=_stale_contacts_query,
        cta_kwargs=lambda user, contact: {"contact_id": contact.id},
    ),
    FillerDefinition(
        key="FILL-CON-04",
        tier=TIER_CONTACT,
        title="Add an occasion for {contact}",
        reason_text="No birthday, closing date, or anniversary on file yet -- add one so this contact can start qualifying for suggestions.",
        cta_label="Add an occasion",
        cta_endpoint="contacts.view_contact",
        per_contact=True,
        contact_query=_contacts_missing_occasion_query,
        cta_kwargs=lambda user, contact: {"contact_id": contact.id},
    ),
    FillerDefinition(
        key="FILL-CON-05",
        tier=TIER_CONTACT,
        title="Add a shipping address for {contact}",
        reason_text="A gift can't ship without a shipping address on file.",
        cta_label="Add address",
        cta_endpoint="contacts.edit_contact",
        per_contact=True,
        contact_query=_contacts_missing_shipping_query,
        cta_kwargs=lambda user, contact: {"contact_id": contact.id},
    ),

    FillerDefinition(
        key="FILL-DIS-01",
        tier=TIER_DISCOVERY,
        title="Review new gifts in the catalog",
        reason_text="Browse the gift catalog to see what's available to send.",
        cta_label="Browse catalog",
        cta_endpoint="catalog.list_catalog",
        condition=lambda user: True,
    ),
    FillerDefinition(
        key="FILL-DIS-03",
        tier=TIER_DISCOVERY,
        title="Build your first Flow",
        reason_text="Flows automatically suggest gifts and outreach when a contact hits a milestone.",
        cta_label="Build a Flow",
        cta_endpoint="campaigns.campaign_new",
        condition=_no_flows,
    ),
    FillerDefinition(
        key="FILL-DIS-04",
        tier=TIER_DISCOVERY,
        title="Browse the Flow Library",
        reason_text="Start from a ready-made Flow template instead of building one from scratch.",
        cta_label="Browse Flow Library",
        cta_endpoint="campaigns.recipe_book",
        condition=_no_flows,
    ),
]

_REGISTRY_BY_KEY = {d.key: d for d in REGISTRY}


def generate_filler_cards(user, limit):
    """Return up to `limit` FillerCard objects for `user`'s Today tab, in
    tier order (account -> contact -> discovery), skipping anything
    already resolved (dismissed or actioned) for this user. `limit` is
    however many cards short of TARGET_CARD_COUNT the real queue
    (SuggestedAction + FlowRecommendation) already is -- filler only
    tops that up, it never displaces a real card."""
    if limit <= 0:
        return []

    resolved_keys = {
        row.filler_key for row in FillerActionState.query.filter_by(user_id=user.id).all()
    }

    cards = []
    for definition in sorted(REGISTRY, key=lambda d: d.tier):
        if len(cards) >= limit:
            break

        if definition.per_contact:
            shown = 0
            for contact in definition.contact_query(user):
                if len(cards) >= limit or shown >= MAX_PER_CONTACT_CARDS:
                    break
                key = f"{definition.key}:{contact.id}"
                if key in resolved_keys:
                    continue
                cards.append(FillerCard(
                    key=key,
                    tier=definition.tier,
                    title=definition.title.format(contact=contact.household_name),
                    reason_text=definition.reason_text,
                    cta_label=definition.cta_label,
                    cta_url=_build_url(definition, user, contact),
                    contact=contact,
                ))
                shown += 1
        else:
            if definition.key in resolved_keys:
                continue
            if not definition.condition(user):
                continue
            cards.append(FillerCard(
                key=definition.key,
                tier=definition.tier,
                title=definition.title,
                reason_text=definition.reason_text,
                cta_label=definition.cta_label,
                cta_url=_build_url(definition, user),
            ))

    return cards[:limit]


def resolve_target_url(user, filler_key):
    """Given a filler_key (possibly "<BASE_KEY>:<contact_id>" for a
    per-contact filler), return the URL its CTA button should go to.
    Doesn't re-check the underlying condition -- once an agent taps the
    card we send them to the CTA regardless of whether a fresh query
    would still technically match (e.g. someone else just added the
    missing shipping address a second ago)."""
    base_key, _, contact_id = filler_key.partition(":")
    definition = _REGISTRY_BY_KEY.get(base_key)
    if not definition:
        return None
    if contact_id:
        from app.models import Contact
        contact = Contact.query.get(contact_id)
        if not contact:
            return None
        return _build_url(definition, user, contact)
    return _build_url(definition, user)


def record_resolution(user, filler_key, status):
    """Marks a filler card resolved (dismissed or actioned) so it never
    reappears for this user. A no-op if it's somehow already resolved
    (e.g. a double form submit) -- the original record wins."""
    existing = FillerActionState.query.filter_by(user_id=user.id, filler_key=filler_key).first()
    if existing:
        return
    db.session.add(FillerActionState(
        org_id=user.org_id,
        user_id=user.id,
        filler_key=filler_key,
        status=status,
        resolved_at=datetime.utcnow(),
    ))
    db.session.commit()
