"""add multi-user org support

Revision ID: 6a95aac36c8f
Revises: dbe292b8bc32
Create Date: 2026-07-08 09:24:55.610834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a95aac36c8f'
down_revision = 'dbe292b8bc32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_contacts_owner_user_id'), ['owner_user_id'], unique=False)
        # Named explicitly (rather than the autogenerated None) so Alembic's
        # SQLite batch mode -- which rebuilds the table rather than altering
        # it in place, and needs a real name to do that bookkeeping -- can
        # create/drop this constraint. Unnamed works fine on MySQL but
        # breaks a from-scratch `flask db upgrade` against local SQLite
        # with "ValueError: Constraint must have a name".
        batch_op.create_foreign_key('fk_contacts_owner_user_id_users', 'users', ['owner_user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('active', 'pending', 'disabled', name='user_status'), nullable=False))
        batch_op.add_column(sa.Column('invite_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('invite_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invited_by_user_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_invite_token'), ['invite_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_users_invited_by_user_id_users', 'users', ['invited_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_invited_by_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_invite_token'))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('invited_by_user_id')
        batch_op.drop_column('invite_expires_at')
        batch_op.drop_column('invite_token')
        batch_op.drop_column('status')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contacts_owner_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contacts_owner_user_id'))
        batch_op.drop_column('owner_user_id')

    # ### end Alembic commands ###
