"""Initial schema

Revision ID: dbe292b8bc32
Revises: 
Create Date: 2026-07-07 16:42:13.459501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe292b8bc32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('orgs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Enum('free', 'starter', 'pro', 'team', name='org_tier'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('billing_type', sa.Enum('card', 'net30', 'net60', name='billing_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('household_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('new', 'active', 'past', name='contact_status'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_status'), ['status'], unique=False)

    op.create_table('gift_catalog_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('interest_tags', sa.String(length=500), nullable=True),
    sa.Column('shopify_product_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gift_catalog_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gift_catalog_items_org_id'), ['org_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('admin', 'agent', name='user_role'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('contact_interests',
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('interest_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.PrimaryKeyConstraint('contact_id', 'interest_id')
    )
    op.create_table('contact_people',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('household_role', sa.Enum('head', 'spouse', 'other', name='household_role'), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_people_contact_id'), ['contact_id'], unique=False)

    op.create_table('gift_triggers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('interest_tag', sa.String(length=100), nullable=True),
    sa.Column('suggested_gift_id', sa.String(length=36), nullable=True),
    sa.Column('default_reason_template', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['suggested_gift_id'], ['gift_catalog_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gift_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gift_triggers_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_gift_triggers_org_id'), ['org_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_rule', sa.Enum('annual', 'none', name='recurrence_rule'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_event_date'), ['event_date'], unique=False)

    op.create_table('contact_methods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('method_type', sa.Enum('email', 'phone', name='method_type'), nullable=False),
    sa.Column('subtype', sa.Enum('personal', 'work', 'mobile', 'home', name='method_subtype'), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['contact_people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_methods_person_id'), ['person_id'], unique=False)

    op.create_table('suggested_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('triggering_event_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.Enum('gift', 'email', 'text', name='suggested_action_type'), nullable=False),
    sa.Column('suggested_gift_id', sa.String(length=36), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'skipped', 'sent', name='suggested_action_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['suggested_gift_id'], ['gift_catalog_items.id'], ),
    sa.ForeignKeyConstraint(['triggering_event_id'], ['timeline_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggested_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggested_actions_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggested_actions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggested_actions_status'), ['status'], unique=False)

    op.create_table('action_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('suggested_action_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.Enum('gift', 'email', 'text', name='action_log_type'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['suggested_action_id'], ['suggested_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_log_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_log_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_log_org_id'))
        batch_op.drop_index(batch_op.f('ix_action_log_contact_id'))

    op.drop_table('action_log')
    with op.batch_alter_table('suggested_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggested_actions_status'))
        batch_op.drop_index(batch_op.f('ix_suggested_actions_org_id'))
        batch_op.drop_index(batch_op.f('ix_suggested_actions_contact_id'))

    op.drop_table('suggested_actions')
    with op.batch_alter_table('contact_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_methods_person_id'))

    op.drop_table('contact_methods')
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_contact_id'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('gift_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gift_triggers_org_id'))
        batch_op.drop_index(batch_op.f('ix_gift_triggers_event_type'))

    op.drop_table('gift_triggers')
    with op.batch_alter_table('contact_people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_people_contact_id'))

    op.drop_table('contact_people')
    op.drop_table('contact_interests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('gift_catalog_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gift_catalog_items_org_id'))

    op.drop_table('gift_catalog_items')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_status'))
        batch_op.drop_index(batch_op.f('ix_contacts_org_id'))

    op.drop_table('contacts')
    op.drop_table('orgs')
    op.drop_table('interests')
    # ### end Alembic commands ###
