from datetime import datetime
from app.extensions import db
from app.models.org import gen_uuid


class SuggestedAction(db.Model):
    """
    A single card on the agent's daily dashboard: 'reach out to X because Y,
    here's a suggested gift/email/text'. Generated by the nightly job,
    approved/edited/skipped by the agent.
    """
    __tablename__ = "suggested_actions"

    id = db.Column(db.String(36), primary_key=True, default=gen_uuid)
    org_id = db.Column(db.String(36), db.ForeignKey("orgs.id"), nullable=False, index=True)
    contact_id = db.Column(db.String(36), db.ForeignKey("contacts.id"), nullable=False, index=True)
    triggering_event_id = db.Column(db.String(36), db.ForeignKey("timeline_events.id"), nullable=True)
    # Set when this suggestion came from the campaign engine (stage 3);
    # NULL for suggestions generated by the older GiftTrigger path.
    source_campaign_id = db.Column(db.String(36), db.ForeignKey("campaigns.id"), nullable=True, index=True)

    action_type = db.Column(
        db.Enum("gift", "email", "text", "handwritten_note", name="suggested_action_type"), nullable=False
    )
    suggested_gift_id = db.Column(db.String(36), db.ForeignKey("gift_catalog_items.id"), nullable=True)

    reason_text = db.Column(db.Text, nullable=False)  # the human-readable "why", LLM or template generated
    # The actual customer-facing copy for email/text/handwritten_note actions
    # (LLM-written or template-rendered). NULL for gift-only actions and for
    # older GiftTrigger-generated suggestions that predate this field.
    generated_message = db.Column(db.Text, nullable=True)
    target_date = db.Column(db.Date, nullable=False)  # the date of the event this relates to

    status = db.Column(
        db.Enum("pending", "approved", "skipped", "sent", "deleted", name="suggested_action_status"),
        default="pending",
        index=True,
    )

    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    resolved_at = db.Column(db.DateTime, nullable=True)  # when approved/skipped

    contact = db.relationship("Contact")
    triggering_event = db.relationship("TimelineEvent")
    suggested_gift = db.relationship("GiftCatalogItem")
    source_campaign = db.relationship("Campaign")

    @property
    def owning_agent(self):
        """Best guess at which agent this suggestion 'belongs to', for the
        actions report and its per-agent filter: the flow's owner if it
        came from a personal flow, else whoever privately owns the
        contact. None for a shared contact with no owning flow -- those
        are org-wide/legacy and aren't any one agent's."""
        if self.source_campaign_id:
            return self.source_campaign.owner if self.source_campaign else None
        return self.contact.owner if self.contact else None


class ActionLog(db.Model):
    """
    Permanent record of what was actually sent -- for agent history,
    spend tracking / tax export, and to avoid duplicate suggestions.
    """
    __tablename__ = "action_log"

    id = db.Column(db.String(36), primary_key=True, default=gen_uuid)
    org_id = db.Column(db.String(36), db.ForeignKey("orgs.id"), nullable=False, index=True)
    contact_id = db.Column(db.String(36), db.ForeignKey("contacts.id"), nullable=False, index=True)
    suggested_action_id = db.Column(db.String(36), db.ForeignKey("suggested_actions.id"), nullable=True)

    action_type = db.Column(db.Enum("gift", "email", "text", "handwritten_note", name="action_log_type"), nullable=False)
    detail = db.Column(db.Text, nullable=True)  # e.g. gift name + price, or email subject line
    cost_cents = db.Column(db.Integer, nullable=True)  # for spend tracking / tax export

    # Automated-send tracking. NULL for action types that aren't wired up to
    # an actual send yet (gift fulfillment, text, handwritten_note) -- those
    # stay manual for now, so this column simply doesn't apply to them.
    # "email" is the first channel with a real send behind it (SendGrid);
    # 'sent' / 'failed' record whether that actually went out, with the
    # reason in delivery_error when it didn't.
    delivery_status = db.Column(db.Enum("sent", "failed", name="action_log_delivery_status"), nullable=True)
    delivery_error = db.Column(db.Text, nullable=True)

    # Which agent actually approved this -- used for the "who did what"
    # column/filter on the org-wide actions report. Nullable because it's
    # only set going forward (backfilled from ContactAuditLog for existing
    # rows where that history exists); a NULL here just means "unknown",
    # not "nobody".
    approved_by_user_id = db.Column(db.String(36), db.ForeignKey("users.id"), nullable=True, index=True)

    sent_at = db.Column(db.DateTime, default=datetime.utcnow)

    contact = db.relationship("Contact")
    suggested_action = db.relationship("SuggestedAction")
    approved_by = db.relationship("User", foreign_keys=[approved_by_user_id])

    @property
    def owning_agent(self):
        """Who to credit this completed action to: whoever actually
        approved it if we know that, else fall back to the suggestion's
        owning agent (covers old rows from before approved_by_user_id
        existed, in the rare case the backfill didn't find a match)."""
        if self.approved_by_user_id:
            return self.approved_by
        return self.suggested_action.owning_agent if self.suggested_action else None
