from datetime import date, datetime, timedelta
from app.extensions import db
from app.models.org import gen_uuid

# How many days past target_date a pending suggestion is allowed to sit
# before the nightly job auto-expires it (see expire_stale_suggestions in
# app/services/suggestion_engine.py). Hardcoded for now rather than a
# per-org setting -- easy to promote later if agencies want it tuned.
EXPIRATION_GRACE_DAYS = 10


class SuggestedAction(db.Model):
    """
    A single card on the agent's daily dashboard: 'reach out to X because Y,
    here's a suggested gift/email/text'. Generated by the nightly job,
    approved/edited/skipped by the agent.
    """
    __tablename__ = "suggested_actions"

    id = db.Column(db.String(36), primary_key=True, default=gen_uuid)
    org_id = db.Column(db.String(36), db.ForeignKey("orgs.id"), nullable=False, index=True)
    contact_id = db.Column(db.String(36), db.ForeignKey("contacts.id"), nullable=False, index=True)
    triggering_event_id = db.Column(db.String(36), db.ForeignKey("timeline_events.id"), nullable=True)
    # Set when this suggestion came from the campaign engine (stage 3);
    # NULL for suggestions generated by the older GiftTrigger path.
    source_campaign_id = db.Column(db.String(36), db.ForeignKey("campaigns.id"), nullable=True, index=True)

    action_type = db.Column(
        db.Enum("gift", "email", "text", "handwritten_note", name="suggested_action_type"), nullable=False
    )
    suggested_gift_id = db.Column(db.String(36), db.ForeignKey("gift_catalog_items.id"), nullable=True)

    reason_text = db.Column(db.Text, nullable=False)  # the human-readable "why", LLM or template generated
    # The actual customer-facing copy for email/text/handwritten_note actions
    # (LLM-written or template-rendered). NULL for gift-only actions and for
    # older GiftTrigger-generated suggestions that predate this field.
    generated_message = db.Column(db.Text, nullable=True)
    target_date = db.Column(db.Date, nullable=False)  # the date of the event this relates to

    status = db.Column(
        db.Enum("pending", "approved", "skipped", "sent", "deleted", "expired", name="suggested_action_status"),
        default="pending",
        index=True,
    )

    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    resolved_at = db.Column(db.DateTime, nullable=True)  # when approved/skipped

    contact = db.relationship("Contact")
    triggering_event = db.relationship("TimelineEvent")
    suggested_gift = db.relationship("GiftCatalogItem")
    source_campaign = db.relationship("Campaign")

    @property
    def owning_agent(self):
        """Best guess at which agent this suggestion 'belongs to', for the
        actions report and its per-agent filter: the flow's owner if it
        came from a personal flow, else whoever privately owns the
        contact. None for a shared contact with no owning flow -- those
        are org-wide/legacy and aren't any one agent's."""
        if self.source_campaign_id:
            return self.source_campaign.owner if self.source_campaign else None
        return self.contact.owner if self.contact else None

    @property
    def expires_on(self):
        """The date after which, if still pending, the nightly job will
        auto-expire this suggestion (see expire_stale_suggestions in
        app/services/suggestion_engine.py). Shown on the dashboard card so
        the agent knows there's a clock on it -- not just informational
        after the fact."""
        return self.target_date + timedelta(days=EXPIRATION_GRACE_DAYS)

    @property
    def gift_timing(self):
        """For a gift suggestion with a resolved catalog item, how much
        runway is left to approve it and still have it ship in time for
        target_date -- based on the gift's lead_time_days (order-to-ship,
        not a delivery promise; we don't control carrier transit time).

        Returns None for non-gift actions or a gift with no catalog item
        resolved yet (nothing to compute a lead time from). Otherwise a
        dict: {order_by, days_left, urgency}, where urgency is one of:
          - "late": order_by has already passed and this is still pending
          - "urgent": needs to be approved today (0 days left)
          - "soon": 1-2 days left
          - "ok": 3+ days left
        """
        if self.action_type != "gift" or not self.suggested_gift:
            return None

        order_by = self.target_date - timedelta(days=self.suggested_gift.lead_time_days)
        days_left = (order_by - date.today()).days

        if days_left < 0:
            urgency = "late"
        elif days_left == 0:
            urgency = "urgent"
        elif days_left <= 2:
            urgency = "soon"
        else:
            urgency = "ok"

        return {"order_by": order_by, "days_left": days_left, "urgency": urgency}



class ActionLog(db.Model):
    """
    Permanent record of what was actually sent -- for agent history,
    spend tracking / tax export, and to avoid duplicate suggestions.
    """
    __tablename__ = "action_log"

    id = db.Column(db.String(36), primary_key=True, default=gen_uuid)
    org_id = db.Column(db.String(36), db.ForeignKey("orgs.id"), nullable=False, index=True)
    contact_id = db.Column(db.String(36), db.ForeignKey("contacts.id"), nullable=False, index=True)
    suggested_action_id = db.Column(db.String(36), db.ForeignKey("suggested_actions.id"), nullable=True)

    action_type = db.Column(db.Enum("gift", "email", "text", "handwritten_note", name="action_log_type"), nullable=False)
    detail = db.Column(db.Text, nullable=True)  # e.g. gift name + price, or email subject line
    cost_cents = db.Column(db.Integer, nullable=True)  # for spend tracking / tax export

    # Automated-send tracking. NULL for action types that aren't wired up to
    # an actual send yet (gift fulfillment, text, handwritten_note) -- those
    # stay manual for now, so this column simply doesn't apply to them.
    # "email" is the first channel with a real send behind it (SendGrid);
    # 'sent' / 'failed' record whether that actually went out, with the
    # reason in delivery_error when it didn't.
    delivery_status = db.Column(db.Enum("sent", "failed", name="action_log_delivery_status"), nullable=True)
    delivery_error = db.Column(db.Text, nullable=True)

    # Which agent actually approved this -- used for the "who did what"
    # column/filter on the org-wide actions report. Nullable because it's
    # only set going forward (backfilled from ContactAuditLog for existing
    # rows where that history exists); a NULL here just means "unknown",
    # not "nobody".
    approved_by_user_id = db.Column(db.String(36), db.ForeignKey("users.id"), nullable=True, index=True)

    sent_at = db.Column(db.DateTime, default=datetime.utcnow)

    contact = db.relationship("Contact")
    suggested_action = db.relationship("SuggestedAction")
    approved_by = db.relationship("User", foreign_keys=[approved_by_user_id])

    @property
    def owning_agent(self):
        """Who to credit this completed action to: whoever actually
        approved it if we know that, else fall back to the suggestion's
        owning agent (covers old rows from before approved_by_user_id
        existed, in the rare case the backfill didn't find a match)."""
        if self.approved_by_user_id:
            return self.approved_by
        return self.suggested_action.owning_agent if self.suggested_action else None
