from datetime import datetime
from app.extensions import db
from app.models.org import gen_uuid


class SuggestedAction(db.Model):
    """
    A single card on the agent's daily dashboard: 'reach out to X because Y,
    here's a suggested gift/email/text'. Generated by the nightly job,
    approved/edited/skipped by the agent.
    """
    __tablename__ = "suggested_actions"

    id = db.Column(db.String(36), primary_key=True, default=gen_uuid)
    org_id = db.Column(db.String(36), db.ForeignKey("orgs.id"), nullable=False, index=True)
    contact_id = db.Column(db.String(36), db.ForeignKey("contacts.id"), nullable=False, index=True)
    triggering_event_id = db.Column(db.String(36), db.ForeignKey("timeline_events.id"), nullable=True)

    action_type = db.Column(
        db.Enum("gift", "email", "text", name="suggested_action_type"), nullable=False
    )
    suggested_gift_id = db.Column(db.String(36), db.ForeignKey("gift_catalog_items.id"), nullable=True)

    reason_text = db.Column(db.Text, nullable=False)  # the human-readable "why", LLM or template generated
    target_date = db.Column(db.Date, nullable=False)  # the date of the event this relates to

    status = db.Column(
        db.Enum("pending", "approved", "skipped", "sent", name="suggested_action_status"),
        default="pending",
        index=True,
    )

    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    resolved_at = db.Column(db.DateTime, nullable=True)  # when approved/skipped

    contact = db.relationship("Contact")
    triggering_event = db.relationship("TimelineEvent")
    suggested_gift = db.relationship("GiftCatalogItem")


class ActionLog(db.Model):
    """
    Permanent record of what was actually sent -- for agent history,
    spend tracking / tax export, and to avoid duplicate suggestions.
    """
    __tablename__ = "action_log"

    id = db.Column(db.String(36), primary_key=True, default=gen_uuid)
    org_id = db.Column(db.String(36), db.ForeignKey("orgs.id"), nullable=False, index=True)
    contact_id = db.Column(db.String(36), db.ForeignKey("contacts.id"), nullable=False, index=True)
    suggested_action_id = db.Column(db.String(36), db.ForeignKey("suggested_actions.id"), nullable=True)

    action_type = db.Column(db.Enum("gift", "email", "text", name="action_log_type"), nullable=False)
    detail = db.Column(db.Text, nullable=True)  # e.g. gift name + price, or email subject line
    cost_cents = db.Column(db.Integer, nullable=True)  # for spend tracking / tax export

    sent_at = db.Column(db.DateTime, default=datetime.utcnow)

    contact = db.relationship("Contact")
